version: "3"

services:

  php-fpm:
    image: php-fpm
    build: ./docker/php-fpm
    depends_on:
      - sql
      - redis
    volumes:
      - ./:/var/www
      - ./storage/docker/php/log:/var/log/php
    environment:
      CONTAINER_ROLE: app
      PHP_OPCACHE_ENABLE: 1

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: prod/Dockerfile
    depends_on:
      - php-fpm
    ports:
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./storage/docker/nginx/logs:/var/log/nginx

  sql:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - sql:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  meilisearch:
    image: getmeili/meilisearch:v0.23.0
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/data.ms
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  sql:
    driver: local
  meilisearch:
    driver: local
